default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_morocco_development

test:
  <<: *default
  database: rails_morocco_test

production:
  <<: *default
  database: rails_morocco_production
  username: rails_morocco
  password: <%= ENV['RAILS_MOROCCO_DATABASE_PASSWORD'] %>
